### PR TITLE
BytePairTokenizer must not split sequences of \n

### PR DESCRIPTION
**Pull request by martin-gorner**
Llama3-instruct uses the sequence "\n\n" in its chat template (see [Llama docs](https://www.llama.com/docs/model-cards-and-prompt-formats/meta-llama-3/#llama-3-instruct)). It must be tokenized as a whole for the chat template to work. Unfortunately, BytePairTokenizer splits "\n\n" into "\n" "\n" before actual tokenization which results in different tokens.

This fix corrects this and makes chatting with Llama3-instruct possible.
Hopefully, the impact on other models is minimal.

### CODE REVIEW

**Comment by martin-gorner** [comment]
llama.cpp had a similar issue:
https://github.com/ggerganov/llama.cpp/issues/6809

**Comment by martin-gorner** [comment]
btw, the byte_pair_tokenizer test is marked as "large" and therefore does not run in most cases. I did run it manually and successfully with the changes. There does not seem to be anything "large" about it so consider removing the marker.

**Comment by martin-gorner** [comment]
The Deeplabv3 test failure does not seem to be related to this PR... There isn't much I can do to fix it.

**Review by divyashreepathihalli — APPROVED** [review]
LGTM! thanks Martin!

**Pull request merged**
