### PR TITLE
Support Gemma2 checkpoint conversion

### LINKED ISSUE #1691: Conversion script modification for Gemma 2 models
**Is your feature request related to a problem? Please describe.**
I am trying to convert a keras Gemma model after training to HF trasnformers , so that it  can be used in VLLM , for faster inference. There is a script which can convert Gemma model to transformers at tools/gemma/export_gemma_to_hf.py but it is outdated. 

**Describe the solution you'd like**
If someone can modify it for Gemma2 models. And also write a script for LLAMA 3 models as I suppose these two are majorly used, and there is not a faster continous batching alternative in keras nlp ecosystem. 

**Describe alternatives you've considered**

**Additional context**

Here is the script [https://github.com/keras-team/keras-nlp/blob/master/tools/gemma/export_gemma_to_hf.py](url)

### PR DESCRIPTION
**Pull request by jeffcarp**
Fixes #1691

- Adds Gemma 2 presets to the existing Gemma export script
- Adds `gemma_version` flag

Tested Gemma 1 & 2 (2B):

```
$ python tools/gemma/export_gemma_to_hf.py --gemma_version 2 --preset gemma2_2b_en --size 2b --output_dir /tmp/keras_hf_model/

$ python tools/gemma/export_gemma_to_hf.py --gemma_version 1 --preset gemma_2b_en --size 2b --output_dir /tmp/keras_hf_model/
```

### CODE REVIEW

**Review by divyashreepathihalli — APPROVED** [review]
LGTM!

**Comment by divyashreepathihalli** [comment]
you would need to run `./shell/format.sh` to resolve the code format error.

**Comment by jeffcarp** [comment]
Done. Thanks!

**Comment by jeffcarp** [comment]
Can you or someone with permissions merge the PR?

**Pull request merged**
